### ISSUE TITLE
The leftmost pinned column looks awful in dark mode.

### ISSUE THREAD

**Issue by eshapiro42** [eshapiro42/OctoPrint-Wyze#1]
![OctoPrint-Wyze-dark-mode](https://user-images.githubusercontent.com/11021129/158882357-3e03bf22-55fb-4f5f-8c75-aa7193f01dd2.png)

Maybe add a dark mode toggle to the plugin settings and set the background colors based on that?

**Comment by jneilliii** [comment]
you can just add custom styles to your plugin's css for when a plugin is theming. I've done it with my OctoDash Companion plugin as an example.

https://github.com/jneilliii/OctoPrint-OctoDashCompanion/blob/master/octoprint_octodashcompanion/static/css/octodashcompanion.css

**Comment by eshapiro42** [comment]
@jneilliii Amazing, thanks for the tip!

**Comment by eshapiro42** [comment]
Fixed by e73dc697f7854216d74ee52e6cdefa2f9a905361.
