### ISSUE TITLE
Looks like Wyze may have updated their API/SDK

### ISSUE THREAD

**Issue by Dxniel02** [eshapiro42/OctoPrint-Wyze#13]
I am using:
OctoPrint 1.9.2
Python 3.9.2
OctoPi 1.0.0

**Describe the bug**
I am no longer able to access the plugin interface, it looks like the plugin is no longer able to access Wyze.

go to settings, selected OctoPrint-Wyze plugin, from here I have the email and password fields, I was logged in and able to use the plugin in the past, now it looks like its not signing in and the plugin is not showing me the option to turn on and turn on for certain events. 

**Expected behavior**
I should be able to see and enable the checkboxes for turn on and turn off for certain events like I used to previously.

**Screenshots**
![image](https://github.com/eshapiro42/OctoPrint-Wyze/assets/141685358/07f00068-20d4-47ec-8433-7be497332b7b)
![image](https://github.com/eshapiro42/OctoPrint-Wyze/assets/141685358/dfe3e594-0816-4680-b955-f57f09b89759)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome
  -  Version 115.0.5790.170 (Official Build) (64-bit)

**Comment by tbnorris** [comment]
I can confirm the same issue it was working one day and not the next without updates to OctoPrint.
I am using Pop!_OS (Ubuntu 22.04 LTS based distribution) so I would not think it is dependent on the OS.
I am also running OctoPrint 1.9.2.  I attempted to fix it by rebuilding the OctoPrint install and it still didn't seem to help.

**Comment by eshapiro42** [comment]
Sorry guys, I totally missed this issue somehow. I just moved and still haven't set up my 3D printer, but when I do I will try to reproduce the issue (sounds like it should be easy) and see if anything can be done to fix it.

**Comment by eshapiro42** [comment]
Just fixed this in release [v0.2.2](https://github.com/eshapiro42/OctoPrint-Wyze/releases/tag/v0.2.2). Wyze now requires an API key and key ID to be generated and passed to the server for authentication.

Please install this release and view the new steps in the [Configuration](https://github.com/eshapiro42/OctoPrint-Wyze#configuration) section of the readme.

Sorry it took me so long to get around to fixing this, but better late than never, hopefully!
