### ISSUE TITLE
Multiple Verification Code SMS With No Way to Enter Them

### ISSUE THREAD

**Issue by Darkenvar** [eshapiro42/OctoPrint-Wyze#9]
I just installed this plugin, and am on OctoPi 1.0, so I have Python 3.9.2.  I entered the email and password in the plugin settings. I save it, and then I get 6-8 Verification Code texts from Wyze, but I can't enter them in the plugin or browser to finish authenticating. I tried rebooting the server and same thing on boot. Can't get fully logged into view my devices. I have confirmed it is the right email and password (getting verification SMS also confirms this).

**Comment by eshapiro42** [comment]
Hi, sorry you're having this issue! Unfortunately the `wyze-sdk` library that my plugin is based on has no support for two factor authentication, and without that support I will be unable to get this working for you.

Please feel free to open an issue in the `wyze-sdk` repository requesting support for the web client to allow two factor authentication. If that gets implemented, let me know and I will be happy to revisit this and add the functionality into my plugin.

In the meantime, if you really want to use this plugin you will need to disable two factor authentication on your Wyze account, although obviously this would make your account less secure and I don't really recommend it.

**Comment by Darkenvar** [comment]
Thanks for the feedback. I might look at requesting support on the repository. I will let you know if I get any updates.
